### ISSUE TITLE
permission denied for gdbm

### ISSUE THREAD

**Issue by rmporsch** [ewilazarus/snnm#1]
Hi, first of all thanks a lot for the great tool.  

I noticed a problem which I helped myself with a quick fix but I thought I bring it to your attention.

After installing `snnm` with pip I got he following error when I run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/snnm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/snnm/cli.py", line 56, in main
    synonyms = scrape(args.term)
  File "/usr/local/lib/python3.5/dist-packages/snnm/misc.py", line 12, in wrapper
    cache = shelve.open(_cachepath)
  File "/usr/lib/python3.5/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.5/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.5/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied
```

After looking into `snnm/misc.py` It seems that snnm tries to write temporary files into `__file__` which is write protected.
I helped myself by adding  `__file__ = "/temp"` to `snnm/misc.py` which is not so ideal I guess, but it works.

Is there a better option to solve this?

**Comment by ewilazarus** [comment]
Dear @rmporsch,

I was aware of this problem because it had occured to me as well.

It turns out that I rewrote the tool and as of now, it doesn't attempt to cache anything, anymore. With that being said, you will no longer have such a problem.

Anyways, thanks a lot for using it! If you have a chance, check out the new version v0.2.9:
I removed the output formatting options and caching, but I added some color output and pagination.
